// <auto-generated />
namespace TwelveNote.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixNoteOwnerIdTypo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixNoteOwnerIdTypo));
        
        string IMigrationMetadata.Id
        {
            get { return "202006241951039_FixNoteOwnerIdTypo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
